### ISSUE TITLE
Add support for sending EventService events

### ISSUE THREAD

**Issue by jyundt** [DMTF/Redfish-Tacklebox#132]
Related to [this forum thread](https://redfishforum.com/thread/963/event-service-generator), can $SOMETHING in Tacklebox be extended to send arbitrary events?

**Comment by mraineri** [comment]
@jyundt just to be clear, what I was proposing was we can extend Tacklebox to use the SubmitTestEvent action on a Redfish service so that the service pushes the test event to its subscribers. I wasn't thinking about Tacklebox sending an event directly to the event listener. Is this okay, or do you need something direct without any involvement of a Redfish service?

**Comment by jyundt** [comment]
@mraineri ah got it, thanks for the clarification.

I was actually looking for "Tacklebox sending an event directly to the event listener". I'd like to be able to test our ability to receive events without having to involve another BMC / Redfish service.

**Comment by mraineri** [comment]
Okay, thanks for confirming; I'll need to think about that one a bit...

**Comment by mraineri** [comment]
Closing; new tool merged
