### ISSUE TITLE
Invalid options for rf_power_reset.py

### ISSUE THREAD

**Issue by StackKorora** [DMTF/Redfish-Tacklebox#82]
```
$ rf_power_reset.py -u myuser -p mypass -r https://my.ip.addr --type GracefulRestart
Resetting the system...
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/redfish/bin/rf_power_reset.py", line 49, in <module>
    response = redfish_utilities.system_reset( redfish_obj, args.system, args.type )
  File "/home/user/miniconda3/envs/redfish/lib/python3.7/site-packages/redfish_utilities/systems.py", line 311, in system_reset
    verify_response( response )
  File "/home/user/miniconda3/envs/redfish/lib/python3.7/site-packages/redfish_utilities/messages.py", line 71, in verify_response
    raise RedfishOperationFailedError( "Operation failed: HTTP {}\n{}".format( response.status, exception_string ) )
redfish_utilities.messages.RedfishOperationFailedError: Operation failed: HTTP 400
A general error has occurred. See ExtendedInfo for more information.
The value GracefulRestart for the property ResetType is not in the list of acceptable values.
```
The `-help` lists nine options: `{On,ForceOff,GracefulShutdown,GracefulRestart,ForceRestart,Nmi,ForceOn,PushPowerButton,PowerCycle}`

But, the spec lists twelve options adding Suspend, Pause, and Resume.
https://redfish.dmtf.org/schemas/v1/Resource.json#/definitions/ResetType

However, my system only lists seven: `{On,ForceOff,GracefulShutdown,ForceRestart,Nmi,ForceOn,PushPowerButton}`

Perhaps when a type is called and fails, the system is checked for the list of acceptable values to return to the user.

**Comment by mraineri** [comment]
The script's arguments show possible options defined in the standard so that the user can't enter something completely invalid like "Fred". Some new values were added to the standard in recent months, and those need to be added.

On your particular system, you're correct in that there is a subset of values supported. I can see an additional check to present the user with the supported values when a failure occurs.
