### ISSUE TITLE
Firmware update

### ISSUE THREAD

**Issue by mickaeldotlambertatkontrondotcom** [DMTF/Redfish-Tacklebox#99]
Hello Everyone,

I Hope your doing fine !

From the doc I have, to update the BMC firmware, it shall be like this : 
````
curl -k -s --request POST --url [ROOT_URL] /redfish/v1/UpdateService --header 'Content-Type: application/octet-stream' --upload-file ' [FILE_PATH]'
````

How do I accomplish that using ``rf_update.py`` ?
Using : 
````
rf_update.py $REDFISH_ACCESS  --target /redfish/v1/UpdateService --image ./firmware.tar
````
I got "Service does not support SimpleUpdate".

Thanks !
Have a nice day.
Mickaël.

**Comment by mraineri** [comment]
Can you show the output of the following?

```rf_raw_request.py $REDFISH_ACCESS -req /redfish/v1/UpdateService```

**Comment by mickaeldotlambertatkontrondotcom** [comment]
Sure : 
````
{
    "@odata.id": "/redfish/v1/UpdateService",
    "@odata.type": "#UpdateService.v1_5_0.UpdateService",
    "Description": "Service for Software Update",
    "FirmwareInventory": {
        "@odata.id": "/redfish/v1/UpdateService/FirmwareInventory"
    },
    "HttpPushUri": "/redfish/v1/UpdateService",
    "HttpPushUriOptions": {
        "HttpPushUriApplyTime": {
            "ApplyTime": "Immediate"
        }
    },
    "Id": "UpdateService",
    "MaxImageSizeBytes": 73400320,
    "Name": "Update Service",
    "ServiceEnabled": true
}
````

**Comment by mraineri** [comment]
That's unfortunate... The `rf_update.py` tool is intended to perform updates using either the SimpleUpdate action or the UR referenced by MultipartHttpPushUri; both of these paths are well-defined in Redfish, so we can write standard tooling to work with them.

The service you have only supports HttpPushUri, which can have vendor-specific handling (such as vendor-specific controlling of HTTP headers and the payload itself to transport). We advise in the Redfish Firmware Update White Paper to avoid this path due to interoperability concerns.

I'm hesitant about adding this support to `rf_update.py`, but given the curl sample you provided, I think this should be easy to perform using `rf_raw_request.py` (with some enhancements like supporting a file input). Would this be acceptable to you? It may be worth also providing feedback to the vendor of the system that there are more preferable update paths the industry recommends.

**Comment by mickaeldotlambertatkontrondotcom** [comment]
````
cd $HOME
git clone https://github.com/DMTF/Redfish-Tacklebox
git checkout File-Option-For-Raw
ls -la $(which python3)
lrwxrwxrwx 1 root root 10 août  18  2022 /usr/bin/python3 -> python3.10
...
python3 $HOME/Redfish-Tacklebox/scripts/rf_raw_request.py $REDFISH_ACCESS --request \
  /redfish/v1/UpdateService --method POST -b \
  $File
...
rf_raw_request.py $REDFISH_ACCESS --request /redfish/v1/TaskService/Tasks/1 --method GET | grep percent
            "Message": "The task with id 1 has changed to progress 10 percent complete.",
            "Message": "The task with id 1 has changed to progress 30 percent complete.",
...
````

Worked out like a charm !
We also had an FPGA to upgrade, same method, another file, same results, worked out !
Thanks !-)
